import Foundation
import CoreGraphics

enum BowShape { case longbow, flatbow, holmegaard, recurve, composite, yumi, deflex, pyramid }

struct BowSpec {
    let slug: String
    let name: String
    let place: String
    let era: String
    let timber: String
    let wood: Tone
    let back: Tone
    let shape: BowShape
    let length: Double
    let limbWidth: Double
    let tipWidth: Double
    let draw: Int
    let weight: Int
    let backed: Bool
    let line: String
    let notes: [(String, String)]
}

let bowBook: [BowSpec] = bowA + bowB + bowC

let bowA: [BowSpec] = [
    BowSpec(slug: "englishwarbow", name: "English Warbow", place: "England", era: "1400s",
            timber: "Italian yew", wood: Field.yewHeart, back: Field.yewSap, shape: .longbow,
            length: 1.00, limbWidth: 0.36, tipWidth: 0.30, draw: 32, weight: 150, backed: false,
            line: "Six feet of yew, drawn to the ear, and it takes a lifetime to be able to pull one",
            notes: [("Two woods in one stick", "Yew is the only European timber with a natural laminate: pale sapwood on the back that resists tension, dark heartwood on the belly that resists compression."),
                    ("D section, not flat", "A warbow is deep and narrow, almost round on the belly. All the strength is in the depth, and depth is what makes it heavy."),
                    ("A whip ended tiller", "The outer third bends more than a modern eye expects. Tillered like a flatbow, a warbow of this weight would break."),
                    ("Thirty two inches", "Drawn to the ear rather than the chin. The arrow is a yard long and weighs three ounces.")]),
    BowSpec(slug: "osageflatbow", name: "Osage Flatbow", place: "Great Plains", era: "1800s",
            timber: "Osage orange", wood: Field.osage, back: Field.osageDark, shape: .flatbow,
            length: 0.78, limbWidth: 0.66, tipWidth: 0.22, draw: 28, weight: 55, backed: false,
            line: "Wide, flat, short, and the finest bow wood on earth",
            notes: [("One ring, all the way", "The back is a single growth ring chased down with a drawknife across the whole limb. Violate it anywhere and the bow lifts a splinter there."),
                    ("Width does the work", "A flatbow spreads the strain across a wide thin limb instead of a deep narrow one. It takes less set and it shoots faster for its weight."),
                    ("Yellow, then orange, then brown", "Freshly cut osage is almost fluorescent yellow. It darkens to deep orange in a season and to brown in a decade."),
                    ("It will outlast you", "Osage staves cut a century ago are still being made into bows. Nothing else keeps like it.")]),
    BowSpec(slug: "holmegaard", name: "Holmegaard Bow", place: "Denmark", era: "7000 BC",
            timber: "Elm", wood: Field.elm, back: Field.elm.dk(0.10), shape: .holmegaard,
            length: 0.86, limbWidth: 0.60, tipWidth: 0.12, draw: 26, weight: 50, backed: false,
            line: "Nine thousand years old, and the outer limb is already stiff and narrow",
            notes: [("Stiff outer limbs", "The design puts all the bending in the inner two thirds and leaves the outers as narrow levers. It is the oldest known example of the idea."),
                    ("Mesolithic and modern", "The same principle turns up in every fast bow since. Whoever cut the original had worked out what mass at the tips costs you."),
                    ("Elm, not yew", "Elm is tougher in tension than yew and takes more set. It wants a wider, flatter limb to compensate."),
                    ("Found in a bog", "Peat preserved the wood well enough to measure the section. That is why we know the tiller and not just the outline.")]),
    BowSpec(slug: "meareheath", name: "Meare Heath Bow", place: "Somerset Levels", era: "2600 BC",
            timber: "Yew", wood: Field.yew, back: Field.sinew, shape: .flatbow,
            length: 0.90, limbWidth: 0.72, tipWidth: 0.20, draw: 28, weight: 65, backed: true,
            line: "A wide flat yew bow bound with leather cross straps, from a bog in Somerset",
            notes: [("Wider than any warbow", "Sixty two millimetres across the limb, and flat. It is a different tradition entirely from the medieval longbow."),
                    ("Bound at intervals", "Leather cross bindings at regular spacing, probably to hold a sinew or bark backing that has not survived."),
                    ("Neolithic engineering", "The taper and the section are both worked out. This is not somebody bending a stick; it is a designed object."),
                    ("Yew again", "Even at this date, yew was chosen. The tree that made the warbow was already the best wood available four thousand years earlier.")]),
    BowSpec(slug: "hickoryselfbow", name: "Hickory Selfbow", place: "Eastern Woodlands", era: "1700s",
            timber: "Shagbark hickory", wood: Field.hickory, back: Field.hickory.dk(0.08),
            shape: .pyramid, length: 0.80, limbWidth: 0.70, tipWidth: 0.14, draw: 27, weight: 48,
            backed: false, line: "A pyramid limb: full width at the handle, straight taper to a narrow tip",
            notes: [("Constant thickness", "A pyramid bow tapers only in width. The thickness is the same from handle to tip, and the taper alone makes the tiller."),
                    ("Forgiving to tiller", "Because thickness is constant, a scraper mistake is far less punishing than on a bow that tapers in both directions."),
                    ("Hickory hates damp", "It is superb dry and sluggish wet. A hickory bow left in a damp shed comes out weak and takes set at once."),
                    ("Ring violation matters less", "Unlike osage or yew, hickory will tolerate a back that cuts across rings, which is why it is the beginner's wood.")]),
    BowSpec(slug: "molle", name: "Mollegabet", place: "Denmark", era: "6000 BC",
            timber: "Elm", wood: Field.elm.lt(0.06), back: Field.elm, shape: .holmegaard,
            length: 0.84, limbWidth: 0.56, tipWidth: 0.10, draw: 26, weight: 45, backed: false,
            line: "Half the limb bends and half of it does not, and the tips are almost sticks",
            notes: [("Extreme lever tips", "The outer half is a narrow stiff lever. All the work happens in a short inner limb, which is a hard thing to tiller."),
                    ("Very low tip mass", "Almost no weight at the ends means almost no energy wasted moving the limb itself. It is why the design keeps reappearing."),
                    ("Short working limb", "A short bending section takes more strain per inch. The wood has to be good and the tiller has to be right."),
                    ("Also from a bog", "Danish peat has given us more early bows than anywhere else, and Mollegabet is the type site for the design.")]),
    BowSpec(slug: "sudbury", name: "Sudbury Bow", place: "Massachusetts", era: "1660",
            timber: "Hickory", wood: Field.hickory.dk(0.06), back: Field.hickory.dk(0.14),
            shape: .flatbow, length: 0.82, limbWidth: 0.52, tipWidth: 0.18, draw: 27, weight: 46,
            backed: false, line: "The oldest surviving bow from New England, with a snake head profile",
            notes: [("A widening tip", "The limb narrows and then flares slightly at the nock. It looks decorative and it also stops the nock groove weakening the tip."),
                    ("Taken in 1660", "One of very few Eastern Woodlands bows to survive from the contact period, and the source for hundreds of modern copies."),
                    ("Narrow for a flatbow", "At forty millimetres it sits between the wide plains flatbow and the deep English longbow."),
                    ("Handle bends too", "There is no rigid riser. The whole bow bends, which is normal for the tradition and unusual to a modern eye.")]),
    BowSpec(slug: "penobscot", name: "Penobscot Bow", place: "Maine", era: "1800s",
            timber: "Ash and hickory", wood: Field.ash, back: Field.hickory, shape: .deflex,
            length: 0.86, limbWidth: 0.54, tipWidth: 0.16, draw: 28, weight: 50, backed: true,
            line: "A second small bow strapped to the belly of the first, and nobody agrees why",
            notes: [("Two bows, one string", "A short cable bow is lashed to the belly and its string runs to the main tips. The effect is a compound before compounds."),
                    ("Contested", "Some think it is a genuine early design; others think it is a late curiosity made for collectors. The debate has run for a century."),
                    ("It does work", "Whatever its provenance, the geometry gives a let off at full draw, which is exactly what a modern compound does."),
                    ("Very hard to tiller", "Two bending systems that have to agree with each other, and adjusting one changes the other.")]),
]

let bowB: [BowSpec] = [
    BowSpec(slug: "turkishflight", name: "Turkish Flight Bow", place: "Ottoman", era: "1600s",
            timber: "Horn, sinew and maple", wood: Field.satinwood.lt(0.10), back: Field.sinew, shape: .composite,
            length: 0.52, limbWidth: 0.26, tipWidth: 0.14, draw: 28, weight: 100, backed: true,
            line: "Forty five inches strung, and the flight records it set stood for three hundred years",
            notes: [("Three materials", "Horn on the belly for compression, sinew on the back for tension, a thin maple core to hold them apart. Wood alone cannot do this."),
                    ("Reflexed to a circle", "Unstrung it curls back on itself almost into a ring. Bracing it is a two person job with a stringing frame."),
                    ("A year to build", "The sinew is laid in courses and each course dries for weeks. Nothing about the process can be hurried."),
                    ("Records that stood", "A Turkish flight shot of over 800 metres in the eighteenth century was not beaten with a hand bow until the twentieth.")]),
    BowSpec(slug: "mongol", name: "Mongol Composite", place: "Central Asia", era: "1200s",
            timber: "Horn, sinew and birch", wood: Field.pine.lt(0.06), back: Field.sinew.dk(0.06),
            shape: .composite, length: 0.58, limbWidth: 0.28, tipWidth: 0.16, draw: 30, weight: 90,
            backed: true, line: "Short enough to shoot from a horse and heavy enough to matter when it lands",
            notes: [("Built for horseback", "Length is the enemy on a horse. A composite gets a long draw out of a short bow because horn and sinew store more energy per inch."),
                    ("Rigid siyahs", "The stiff angled tips act as levers and give a let off at full draw, which matters when you hold at anchor on a moving horse."),
                    ("Glue is the weak point", "Fish or hide glue holds it together, and it fails in damp. A composite in a wet climate is a short lived thing."),
                    ("Thumb draw", "Drawn with a ring on the thumb, which puts the arrow on the other side of the bow from a European loose.")]),
    BowSpec(slug: "yumi", name: "Japanese Yumi", place: "Japan", era: "1500s",
            timber: "Bamboo and haze", wood: Field.bamboo, back: Field.bamboo.dk(0.10),
            shape: .yumi, length: 1.00, limbWidth: 0.22, tipWidth: 0.16, draw: 34, weight: 45,
            backed: true, line: "Seven feet, and the hand grips it a third of the way up rather than in the middle",
            notes: [("Asymmetric on purpose", "The grip sits at about a third of the length. The lower limb is short and stiff, the upper long and supple."),
                    ("Laminated bamboo", "Bamboo front and back with hardwood cores glued between. The construction is a thousand years older than modern laminates."),
                    ("It turns in the hand", "On release the bow rotates so the string ends up behind the wrist. The turn is not a fault; it is the design working."),
                    ("Tillered by shaving the core", "Adjustment is made by scraping the wooden cores at the ends, not the bamboo faces.")]),
    BowSpec(slug: "gakgung", name: "Korean Gakgung", place: "Korea", era: "1600s",
            timber: "Horn, sinew, bamboo and oak", wood: Field.bamboo.lt(0.08), back: Field.sinew,
            shape: .composite, length: 0.50, limbWidth: 0.24, tipWidth: 0.14, draw: 30, weight: 55,
            backed: true, line: "The most reflexed bow in the world, and it shoots further for its weight than anything else",
            notes: [("A full circle unstrung", "Off the string it curls into a ring that a hand can hold. There is more stored reflex here than in any other tradition."),
                    ("Water buffalo horn", "Long strips of horn on the belly, sometimes a metre in a single piece, which is why buffalo rather than cattle."),
                    ("Birch bark", "The whole bow is finished in birch bark, which keeps the damp out of the glue lines and takes the decoration."),
                    ("Shot at 145 metres", "Traditional Korean archery targets sit at that distance, which no European wooden bow can reach with accuracy.")]),
    BowSpec(slug: "scythian", name: "Scythian Bow", place: "Pontic Steppe", era: "400 BC",
            timber: "Horn, sinew and wood", wood: Field.ash.lt(0.04), back: Field.sinew.lt(0.04),
            shape: .recurve, length: 0.46, limbWidth: 0.26, tipWidth: 0.14, draw: 26, weight: 60,
            backed: true, line: "Tiny, double curved, and it goes in a case with the arrows",
            notes: [("The gorytos", "Bow and arrows share a single case worn at the hip. A bow that short is the only kind that fits."),
                    ("Sigma shaped", "Braced it makes a shallow S with the tips curving away. Greek writers describe the shape as unmistakable."),
                    ("Very early composite", "Horn and sinew construction is already mature by this date, which means it had been developing for a long time before."),
                    ("Buried with the owner", "Almost everything we know comes from kurgan burials, where the metal fittings survived and the organics did not.")]),
    BowSpec(slug: "bhutan", name: "Bhutanese Bamboo Bow", place: "Bhutan", era: "Traditional",
            timber: "Split bamboo", wood: Field.bamboo.dk(0.06), back: Field.bamboo.lt(0.06),
            shape: .flatbow, length: 0.82, limbWidth: 0.40, tipWidth: 0.18, draw: 27, weight: 45,
            backed: false, line: "One length of split bamboo, and archery is the national sport",
            notes: [("A single split", "Cut from the wall of a large culm so the hard outer skin is the back. Nothing is glued and nothing is laminated."),
                    ("The node matters", "A node in the bending part of the limb is a stiff spot and has to be allowed for when tillering."),
                    ("Shot at 145 metres", "The traditional Bhutanese range is enormous, and matches involve singing, dancing and a great deal of noise."),
                    ("Fast for its weight", "Bamboo has a very high strength to weight ratio, so the limbs can be light and the cast is good.")]),
    BowSpec(slug: "andaman", name: "Andaman Bow", place: "Andaman Islands", era: "Traditional",
            timber: "Chuoi wood", wood: Field.walnut.lt(0.10), back: Field.walnut.dk(0.06),
            shape: .deflex, length: 0.92, limbWidth: 0.44, tipWidth: 0.20, draw: 28, weight: 42,
            backed: false, line: "An S shaped bow with a broad flat handle, unlike anything else",
            notes: [("The S profile", "One limb deflexed and one reflexed, giving an asymmetric shape that is unique to the islands."),
                    ("Wide flat grip", "The handle is a broad paddle rather than a round grip. It is held in a way that no other tradition uses."),
                    ("Shot standing in a canoe", "Much of the use was for fish and turtle from a boat, which explains a great deal about the design."),
                    ("Very little study", "Few examples reached museums and fewer were measured. Most of what is written about them is inference.")]),
    BowSpec(slug: "yewselfbow", name: "Pacific Yew Selfbow", place: "Pacific Northwest", era: "1800s",
            timber: "Pacific yew", wood: Field.yew.lt(0.04), back: Field.yewSap, shape: .flatbow,
            length: 0.76, limbWidth: 0.62, tipWidth: 0.18, draw: 26, weight: 45, backed: false,
            line: "Short, wide and sinew backed in the north, plain in the south",
            notes: [("Denser than European yew", "Slow grown mountain yew with very tight rings, and it takes a shorter, wider bow than a warbow stave would."),
                    ("Sinew where it was wet", "Northern makers backed with sinew against the damp; southern makers often did not bother."),
                    ("Short for the country", "Timber is close in the forest. A long bow is a liability where you shoot between trees."),
                    ("Still the reference wood", "Modern bowyers in North America still rate Pacific yew alongside osage as the two best native bow woods.")]),
]

let bowC: [BowSpec] = [
    BowSpec(slug: "ashlongbow", name: "Ash Longbow", place: "Northern Europe", era: "Medieval",
            timber: "European ash", wood: Field.ash.dk(0.06), back: Field.ash, shape: .longbow,
            length: 0.94, limbWidth: 0.42, tipWidth: 0.26, draw: 28, weight: 60, backed: false,
            line: "What a bow was made of when there was no yew and no money",
            notes: [("The common wood", "Ash is everywhere in Europe and it makes a serviceable bow. Yew was expensive and often imported."),
                    ("Takes set readily", "Ash is strong in tension and weak in compression, so the belly frets and the bow follows the string."),
                    ("Wants width", "A narrow ash longbow will chrysal. Widen the limb and reduce the thickness and it lasts far longer."),
                    ("Rings should be thick", "Unlike yew, ring porous woods like ash want fast growth. Thin rings mean too much soft early wood.")]),
    BowSpec(slug: "elmbow", name: "Elm Bow", place: "Northern Europe", era: "Neolithic onward",
            timber: "Wych elm", wood: Field.elm.dk(0.04), back: Field.elm.lt(0.04), shape: .flatbow,
            length: 0.84, limbWidth: 0.58, tipWidth: 0.18, draw: 27, weight: 48, backed: false,
            line: "The wood of the oldest bows in Europe, and it will not splinter",
            notes: [("Interlocked grain", "Elm grain twists, which makes it a nuisance to split and almost impossible to break in tension."),
                    ("It tolerates violation", "You can cut across rings on the back of an elm bow and get away with it. Try that on yew and it lifts a splinter."),
                    ("Takes more set", "Elm is not stiff. Expect string follow and design the bow to live with it rather than fighting it."),
                    ("Every bog bow", "Holmegaard, Mollegabet and most of the Danish finds are elm. It was the default before yew.")]),
    BowSpec(slug: "hazelbow", name: "Hazel Bow", place: "Britain", era: "Traditional",
            timber: "Hazel", wood: Field.beech.lt(0.06), back: Field.beech, shape: .pyramid,
            length: 0.78, limbWidth: 0.64, tipWidth: 0.16, draw: 26, weight: 40, backed: false,
            line: "Cut from the coppice in the morning and shooting by the evening",
            notes: [("Whole stave, bark on", "A hazel rod of the right diameter needs almost no reduction. The back is simply the outside of the tree."),
                    ("Weak but honest", "It will not make a heavy bow and it will take set. It will make a working bow in an afternoon."),
                    ("Coppice is the point", "Hazel has been cut on rotation in Britain for millennia, and a coppice throws up straight rods of exactly the right size."),
                    ("Season it fast", "Small diameter and thin bark mean it dries in weeks rather than the years a yew stave wants.")]),
    BowSpec(slug: "juniper", name: "Juniper Bow", place: "Great Basin", era: "Traditional",
            timber: "Western juniper", wood: Field.oak.lt(0.10), back: Field.sinew.dk(0.04),
            shape: .flatbow, length: 0.72, limbWidth: 0.66, tipWidth: 0.20, draw: 24, weight: 40,
            backed: true, line: "Sinew backed, because on its own it would break at the first draw",
            notes: [("Weak in tension", "Juniper cannot hold the back together by itself. A heavy sinew backing takes the tension and the wood takes the compression."),
                    ("Superb in compression", "Which is exactly what a sinew backed bow needs from its belly. The pairing is not an accident."),
                    ("Very short", "A metre and a half at most, because sinew allows a shorter bow than wood alone would survive."),
                    ("Months to dry", "A sinew backing takes weeks to cure and the bow gains reflex as it does. It is the last thing to be finished.")]),
    BowSpec(slug: "ipe", name: "Ipe Backed Bow", place: "Modern", era: "Contemporary",
            timber: "Ipe with bamboo backing", wood: Field.walnutDark, back: Field.bamboo,
            shape: .flatbow, length: 0.82, limbWidth: 0.50, tipWidth: 0.16, draw: 28, weight: 50,
            backed: true, line: "Tropical hardwood belly, bamboo back, and it is the modern beginner's bow",
            notes: [("Bombproof in compression", "Ipe is one of the densest timbers in commerce and it resists the belly fretting that kills wooden bows."),
                    ("Bamboo takes the tension", "The pairing splits the job perfectly and the glue line does the rest. It is forgiving of everything except a bad tiller."),
                    ("Cheap and available", "Sold as decking. A bow stave costs a fraction of what a yew billet does and performs nearly as well."),
                    ("Heavy limbs", "The density that makes it strong also makes it slow. It is a fine bow and it is not a fast one.")]),
    BowSpec(slug: "sinewbacked", name: "Sinew Backed Recurve", place: "Great Plains", era: "1800s",
            timber: "Ash with sinew", wood: Field.ash.dk(0.10), back: Field.sinew, shape: .recurve,
            length: 0.62, limbWidth: 0.48, tipWidth: 0.16, draw: 24, weight: 55, backed: true,
            line: "Short, recurved and backed with sinew, for shooting from a horse",
            notes: [("Sinew adds reflex", "As the sinew dries it shrinks and pulls the limbs back into reflex. That stored curve is free energy."),
                    ("Recurved tips", "Steamed and bent forward, so the string lies along the limb at brace and peels off as the bow is drawn."),
                    ("Short because mounted", "Everything about the design comes from having to shoot it from a moving horse at close range."),
                    ("Damp ruins it", "Hide glue and sinew both soften in wet weather. A rain squall can take twenty pounds off the draw weight.")]),
    BowSpec(slug: "cedar", name: "Cedar Backed Bow", place: "Pacific Northwest", era: "Traditional",
            timber: "Yew with cedar", wood: Field.yew.dk(0.06), back: Field.pine.dk(0.04),
            shape: .flatbow, length: 0.80, limbWidth: 0.56, tipWidth: 0.18, draw: 26, weight: 44,
            backed: true, line: "A yew belly under a light cedar back, from a coast where everything is made of cedar",
            notes: [("Light back, heavy belly", "The back only needs to hold together in tension, so a light wood there costs nothing and saves limb mass."),
                    ("Glued with salmon skin", "Traditional glues in the region came from fish. They are strong and they are not waterproof."),
                    ("Painted and bound", "Most surviving examples are decorated, bound at the handle and finished with pitch."),
                    ("Wet climate problems", "Every organic glue in a rainforest is a compromise, which is why so many coastal bows are also sinew wrapped.")]),
    BowSpec(slug: "boardbow", name: "Red Oak Board Bow", place: "Anywhere", era: "Contemporary",
            timber: "Red oak board", wood: Field.oak.lt(0.06), back: Field.oak.lt(0.14),
            shape: .pyramid, length: 0.80, limbWidth: 0.72, tipWidth: 0.14, draw: 26, weight: 40,
            backed: false, line: "A plank from a timber yard, and the first bow almost everybody makes",
            notes: [("Grain run off is the enemy", "A sawn board rarely has grain running the full length. Where it runs off the back, the bow lifts a splinter and breaks."),
                    ("Choose the board carefully", "Look down the edge and reject anything where the lines wander. Half the boards in a stack are unusable."),
                    ("Wide and pyramid", "Maximum width at the handle and a straight taper to the tip. It spreads the strain and forgives a rough tiller."),
                    ("It will teach you everything", "Cheap enough to break without regret, and breaking bows is how the tiller gets learned.")]),
]
